language: node_js
node_js:
  - 10
  - 12
  - 14

cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

stages:
  - compile
  - check
  - test

jobs:
  include:
    - stage: compile
      script: npm run build

    - stage: check
      script: npm run check

    - stage: test
      script: npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
